version: "3.9"

services:
  app:
    build: .
    container_name: country_api
    restart: always
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST} # Provided by Railway plugin
      - DB_USER=${DB_USER} # Provided by Railway plugin
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ./cache:/usr/src/app/cache
    command: ["node", "src/server.js"]

# No local DB service; Railway provides MySQL externally

volumes:
  cache_volume:
